In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import matplotlib.pyplot as plt
import seaborn as sns
import psycopg2

# Connection details
host = 'localhost'
user = 'postgres'
password = quote_plus('Shiv@11$')  # Encode special characters
dbname = 'Data Science Projects'
port = 5432

# Connect to PostgreSQL
engine = create_engine(f"postgresql://{user}:{password}@{host}:{port}/{dbname}")

In [2]:
tables = pd.read_sql("select table_name from information_schema.tables where table_schema = 'public';",engine)
tables

             table_name
0       begin_inventory
1         end_inventory
2       purchase_prices
3             purchases
4                 sales
5        vendor_invoice
6  vendor_sales_summary

In [3]:
for table in tables['table_name']:
    print('-'*50, f'{table}','-'*50)
    print('count of records :', pd.read_sql(f"select count(*) as count from {table}",engine)['count'].values[0])
    display(pd.read_sql(f'select * from {table} limit 5;',engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
count of records : 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
count of records : 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
count of records : 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
count of records : 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
count of records : 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
count of records : 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
count of records : 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [4]:
print('purchase_prices','--'*50)
q1 = pd.read_sql(
    '''SELECT "Brand","Volume","Price" AS "ActualPrice"
    FROM purchase_prices
    ORDER BY "Price" desc LIMIT 5''',engine)
display(q1)


print('purchases','--'*50)
q2 = pd.read_sql(
    '''SELECT  "Brand", "VendorNumber", "VendorName" , "PurchasePrice","Quantity", "Dollars"
    FROM purchases
    ORDER BY "PurchasePrice" desc LIMIT 5''',engine)
display(q2)


print('sales','--'*50)
q3 = pd.read_sql(
    '''SELECT "Brand" ,"VendorNo", "SalesQuantity", "Volume", "ExciseTax","SalesPrice","SalesDollars"
    FROM sales
    ORDER BY "SalesPrice" desc LIMIT 5''',engine)
display(q3)


print('vendor_invoice','--'*50)
q4 = pd.read_sql(
    '''SELECT "VendorNumber" ,"PONumber" ,"Quantity", "Dollars" ,"Freight", "Approval"
    FROM vendor_invoice
    ORDER BY "Dollars" desc LIMIT 5''',engine)
display(q4)

purchase_prices ----------------------------------------------------------------------------------------------------

   Brand Volume  ActualPrice
0   2693    750     13999.90
1   3949    750      7499.99
2   2367   1000      5799.99
3   4423    750      4999.99
4   1991    750      4999.99

purchases ----------------------------------------------------------------------------------------------------

,Brand,VendorNumber,VendorName,PurchasePrice,Quantity,Dollars
0,3949,9165,ULTRA BEVERAGE COMPANY LLP,5681.81,1,5681.81
1,3949,9165,ULTRA BEVERAGE COMPANY LLP,5681.81,1,5681.81
2,3949,9165,ULTRA BEVERAGE COMPANY LLP,5681.81,1,5681.81
3,2367,8112,MOET HENNESSY USA INC,4264.70,1,4264.70
4,2367,8112,MOET HENNESSY USA INC,4264.70,1,4264.70

sales ----------------------------------------------------------------------------------------------------

   Brand  VendorNo  SalesQuantity  Volume  ExciseTax  SalesPrice  SalesDollars
0   2367      8112              1  1000.0       1.05     5799.99       5799.99
1   1991      2561              1   750.0       0.79     4999.99       4999.99
2   1991      2561              1   750.0       0.79     4999.99       4999.99
3    423      8112              1   750.0       0.79     4696.99       4696.99
4    423      8112              1   750.0       0.79     4696.99       4696.99

vendor_invoice ----------------------------------------------------------------------------------------------------

   VendorNumber  PONumber  Quantity     Dollars  Freight        Approval
0          3960     12833    141660  1660435.88  8468.22  Frank Delahunt
1          3960     12618    122740  1468470.64  7048.66  Frank Delahunt
2          3960     12771    127553  1409683.51  7753.26  Frank Delahunt
3          3960     10936    131712  1377224.55  7574.74  Frank Delahunt
4          3960     11191    128861  1354087.31  7041.25  Frank Delahunt

In [5]:
vendor_sales_summary = pd.read_sql_query('''WITH FreightSummary As(
SELECT 
     "VendorNumber", 
     SUM("Freight") AS "FreightCost"
FROM vendor_invoice
GROUP BY "VendorNumber"),

PurchaseSummary AS(
SELECT 
      p."VendorNumber", 
      p."VendorName", 
      p."Brand", 
      p."Description", 
      p."PurchasePrice", 
      pp."Price" AS "ActualPrice", 
      pp."Volume",
SUM(p."Quantity") AS "TotalPurchaseQuantity",
SUM(p."Dollars") AS "TotalPurchaseDollars"
FROM purchases p
JOIN purchase_prices pp
ON p."Brand" = pp."Brand"
WHERE p."PurchasePrice" > 0
GROUP BY p."VendorNumber", p."VendorName", p."Brand", p."Description", p."PurchasePrice", pp."Price", pp."Volume"),

SalesSummary AS(
SELECT 
    "VendorNo", 
    "Brand",
SUM("SalesQuantity") AS "TotalSalesQuantity",
SUM("SalesDollars") AS "TotalSalesDollars",
SUM("SalesPrice") AS "TotalSalesPrice",
SUM("ExciseTax") AS "TotalExciseTax"
FROM sales
GROUP BY "VendorNo", "Brand")

SELECT
     ps."VendorNumber",
     ps."VendorName",
     ps."Brand",
     ps."Description",
     ps."PurchasePrice",
     ps."ActualPrice",
     ps."Volume",
     ps."TotalPurchaseQuantity",
     ps."TotalPurchaseDollars" ,
     ss."TotalSalesQuantity",
     ss."TotalSalesDollars",
     ss."TotalSalesPrice",
     ss."TotalExciseTax",
     fs."FreightCost"
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
ON ps."VendorNumber" = ss."VendorNo"
AND ps."Brand" = ss."Brand"
LEFT JOIN FreightSummary fs
ON ps."VendorNumber" = fs."VendorNumber"
ORDER BY ps."TotalPurchaseDollars" DESC''',engine)

In [6]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080.0,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038.0,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407.0,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682.0,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109.0,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07

In [7]:
vendor_sales_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10692 entries, 0 to 10691
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           10692 non-null  int64
 1   VendorName             10692 non-null  object
 2   Brand                  10692 non-null  int64
 3   Description            10692 non-null  object
 4   PurchasePrice          10692 non-null  float64
 5   ActualPrice            10692 non-null  float64
 6   Volume                 10692 non-null  object
 7   TotalPurchaseQuantity  10692 non-null  float64
 8   TotalPurchaseDollars   10692 non-null  float64
 9   TotalSalesQuantity     10514 non-null  float64
 10  TotalSalesDollars      10514 non-null  float64
 11  TotalSalesPrice        10514 non-null  float64
 12  TotalExciseTax         10514 non-null  float64
 13  FreightCost            10692 non-null  float64
dtypes: float64(9), int64(2), object(3)
memory usage: 1.1+ MB

In [8]:
vendor_sales_summary.describe()

,VendorNumber,Brand,PurchasePrice,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
count,10692.000000,10692.000000,10692.000000,10692.000000,10692.000000,1.069200e+04,10514.000000,1.051400e+04,10514.000000,10514.000000,10692.000000
mean,10650.649458,18039.228769,24.385303,35.643671,3140.886831,3.010669e+04,3129.583317,4.295417e+04,19111.958773,1804.263569,61433.763214
std,18753.519148,12662.187074,109.269375,148.246016,11095.086769,1.230678e+05,11037.801407,1.689778e+05,45264.605387,11065.659557,60938.458032
min,2.000000,58.000000,0.360000,0.490000,1.000000,7.100000e-01,1.000000,1.980000e+00,0.990000,0.060000,0.090000
25%,3951.000000,5793.500000,6.840000,10.990000,36.000000,4.534575e+02,36.000000,8.098200e+02,334.890000,5.382500,14069.870000
50%,7153.000000,18761.500000,10.455000,15.990000,262.000000,3.655465e+03,280.000000,5.599700e+03,3020.085000,50.425000,50293.620000
75%,9552.000000,25514.250000,19.482500,28.990000,1975.750000,2.073824e+04,1985.000000,2.952425e+04,16442.477500,436.730000,79528.990000
max,201359.000000,90631.000000,5681.810000,7499.990000,337660.000000,3.811252e+06,334939.000000,5.101920e+06,672819.310000,368242.800000,257032.070000

In [9]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [10]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [11]:
null_cols = np.array(['TotalSalesQuantity', 'TotalSalesDollars', 'TotalSalesPrice', 'TotalExciseTax'])
vendor_sales_summary[null_cols] = vendor_sales_summary[null_cols].fillna(vendor_sales_summary[null_cols].mean())

In [12]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [13]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']
vendor_sales_summary['ProfitMargin'] = vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars'] * 100
vendor_sales_summary['StockTurnover'] =  vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']
vendor_sales_summary['SalesPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [14]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [15]:
# Auto create table and insert data
# vendor_sales_summary.to_sql("vendor_sales_summary", engine, if_exists="replace", index=False)

In [16]:
pd.read_sql('''SELECT * FROM vendor_sales_summary''',engine).head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080.0,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038.0,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407.0,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682.0,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109.0,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897